name: UpdateModules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: UpdateModules
        run: |
          cd static/img/stuff
          git config --global user.name "PixelOS-Bot"
          git config --global user.email "pixelos.pixelish@gmail.com"
          git checkout main && git pull
          cd -
          git add static/img/stuff
          git commit -m "updating submodule to latest"
          git push 
